//
//  ClipboardMonitor.swift
//  Vault
//
//  macOS has no clipboard notification, so watch the pasteboard's change
//  count. A check is a single integer read, cheap enough to run several
//  times a second.
//

import AppKit
import CryptoKit
import Foundation

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Change count written by Vault itself, so pasting a clip back does not
    /// record it a second time as a fresh copy.
    private var ownChangeCount: Int?

    /// Markers from nspasteboard.org that apps use to ask clipboard managers
    /// not to record a copy (password managers, one-time codes).
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    private static let maxImageBytes = 25 * 1024 * 1024
    private static let maxTextLength = 2_000_000

    private init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.35, repeats: true) { _ in
            Task { @MainActor in ClipboardMonitor.shared.check() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Call right after Vault writes to the pasteboard.
    func noteOwnWrite() {
        ownChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    private func check() {
        let settings = AppSettings.shared
        if let until = settings.pausedUntil, until <= .now { settings.pausedUntil = nil }

        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard count != ownChangeCount else { return }

        guard !settings.isPaused else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard !types.isEmpty else { return }
        if settings.ignoreConcealed, !types.isDisjoint(with: Self.concealedTypes) { return }

        let source = NSWorkspace.shared.frontmostApplication
        guard !settings.isExcluded(source?.bundleIdentifier) else { return }

        guard var item = capture(types: types, settings: settings) else { return }
        // System processes in front (the lock screen, for example) are not
        // a meaningful source.
        if let source, source.activationPolicy == .regular {
            item.sourceBundleID = source.bundleIdentifier
            item.sourceAppName = source.localizedName
        }
        HistoryStore.shared.add(item)
        if settings.playSounds { NSSound(named: "Pop")?.play() }
    }

    private func capture(types: Set<String>, settings: AppSettings) -> ClipItem? {
        // Files first: Finder also puts the file name on the pasteboard as
        // text, which is not what anyone meant to copy.
        if settings.captureFiles,
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipItem(
                kind: .file,
                text: paths.joined(separator: "\n"),
                filePaths: paths,
                contentHash: Self.hash("file", Data(paths.joined(separator: "\n").utf8))
            )
        }

        let string = pasteboard.string(forType: .string)
        let hasImage = types.contains(NSPasteboard.PasteboardType.png.rawValue)
            || types.contains(NSPasteboard.PasteboardType.tiff.rawValue)

        // An image with no text is a picture. Browsers put both on the
        // pasteboard when copying an image; the picture is what people want.
        let preferImage = hasImage && settings.captureImages
            && (string == nil || (!looksLikeRichText(types) && (string?.count ?? 0) < 2048))
        if preferImage {
            if let item = captureImage() { return item }
        }

        guard let string, !string.isEmpty, string.count <= Self.maxTextLength else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        let kind = Self.classify(trimmed)
        var item = ClipItem(kind: kind, text: string, contentHash: Self.hash("text", Data(string.utf8)))
        if kind == .text, let rtf = pasteboard.data(forType: .rtf), rtf.count < 4 * 1024 * 1024 {
            item.rtfBlob = HistoryStore.shared.writeBlob(rtf, ext: "rtf")
        }
        return item
    }

    private func looksLikeRichText(_ types: Set<String>) -> Bool {
        types.contains(NSPasteboard.PasteboardType.rtf.rawValue) || types.contains(NSPasteboard.PasteboardType.html.rawValue)
    }

    private func captureImage() -> ClipItem? {
        let png: Data
        if let data = pasteboard.data(forType: .png) {
            png = data
        } else if let tiff = pasteboard.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: tiff),
                  let data = rep.representation(using: .png, properties: [:]) {
            png = data
        } else {
            return nil
        }
        guard png.count <= Self.maxImageBytes,
              let rep = NSBitmapImageRep(data: png),
              let blob = HistoryStore.shared.writeBlob(png, ext: "png") else { return nil }
        return ClipItem(
            kind: .image,
            imageBlob: blob,
            imageWidth: rep.pixelsWide,
            imageHeight: rep.pixelsHigh,
            byteSize: png.count,
            contentHash: Self.hash("image", png)
        )
    }

    static func classify(_ text: String) -> ClipKind {
        if text.count <= 64, ColorValue(parsing: text) != nil { return .color }
        if !text.contains(where: \.isWhitespace),
           let url = URL(string: text),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto", "ssh"].contains(scheme),
           url.host != nil || scheme == "mailto" {
            return .link
        }
        return .text
    }

    private static func hash(_ kind: String, _ data: Data) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(kind.utf8))
        hasher.update(data: data)
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
